AWSTemplateFormatVersion: '2010-09-09'
Description: 'Pardon Simulator - CloudWatch Dashboards and Alarms'

Parameters:
  EnvironmentName:
    Type: String
    Default: pardon-production
    Description: Environment name prefix

  AlarmEmail:
    Type: String
    Description: Email address for alarm notifications
    Default: ''

Conditions:
  HasAlarmEmail: !Not [!Equals [!Ref AlarmEmail, '']]

Resources:
  # SNS Topic for Alarms
  AlarmTopic:
    Type: AWS::SNS::Topic
    Condition: HasAlarmEmail
    Properties:
      TopicName: !Sub ${EnvironmentName}-alarms
      DisplayName: Pardon Simulator Alarms
      Subscription:
        - Endpoint: !Ref AlarmEmail
          Protocol: email

  # CloudWatch Dashboard
  Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub ${EnvironmentName}-dashboard
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/ECS", "CPUUtilization", {"stat": "Average"}],
                  [".", "MemoryUtilization", {"stat": "Average"}]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "ECS Resource Utilization",
                "yAxis": {
                  "left": {"min": 0, "max": 100}
                }
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/ApplicationELB", "TargetResponseTime", {"stat": "Average"}],
                  ["...", {"stat": "p95"}],
                  ["...", {"stat": "p99"}]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "Response Time (ms)",
                "yAxis": {
                  "left": {"min": 0}
                }
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/ApplicationELB", "RequestCount", {"stat": "Sum"}],
                  [".", "HTTPCode_Target_2XX_Count", {"stat": "Sum"}],
                  [".", "HTTPCode_Target_4XX_Count", {"stat": "Sum"}],
                  [".", "HTTPCode_Target_5XX_Count", {"stat": "Sum"}]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "HTTP Requests",
                "yAxis": {
                  "left": {"min": 0}
                }
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/ECS", "RunningTaskCount", {"stat": "Average"}]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "Running ECS Tasks"
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/RDS", "CPUUtilization", {"stat": "Average"}],
                  [".", "DatabaseConnections", {"stat": "Average"}],
                  [".", "FreeableMemory", {"stat": "Average"}]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "RDS Metrics"
              }
            }
          ]
        }

  # Alarm: High CPU Utilization
  HighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasAlarmEmail
    Properties:
      AlarmName: !Sub ${EnvironmentName}-high-cpu
      AlarmDescription: ECS service CPU utilization is too high
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlarmTopic
      Dimensions:
        - Name: ServiceName
          Value: !Sub ${EnvironmentName}-service
        - Name: ClusterName
          Value: !Sub ${EnvironmentName}-cluster

  # Alarm: High Memory Utilization
  HighMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasAlarmEmail
    Properties:
      AlarmName: !Sub ${EnvironmentName}-high-memory
      AlarmDescription: ECS service memory utilization is too high
      MetricName: MemoryUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 85
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlarmTopic
      Dimensions:
        - Name: ServiceName
          Value: !Sub ${EnvironmentName}-service
        - Name: ClusterName
          Value: !Sub ${EnvironmentName}-cluster

  # Alarm: Unhealthy Targets
  UnhealthyTargetsAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasAlarmEmail
    Properties:
      AlarmName: !Sub ${EnvironmentName}-unhealthy-targets
      AlarmDescription: ALB has unhealthy targets
      MetricName: UnHealthyHostCount
      Namespace: AWS/ApplicationELB
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref AlarmTopic

  # Alarm: High 5XX Error Rate
  High5XXAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasAlarmEmail
    Properties:
      AlarmName: !Sub ${EnvironmentName}-high-5xx
      AlarmDescription: High rate of 5XX errors
      MetricName: HTTPCode_Target_5XX_Count
      Namespace: AWS/ApplicationELB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlarmTopic

  # Alarm: RDS High CPU
  RDSHighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasAlarmEmail
    Properties:
      AlarmName: !Sub ${EnvironmentName}-rds-high-cpu
      AlarmDescription: RDS CPU utilization is too high
      MetricName: CPUUtilization
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlarmTopic

  # Alarm: RDS Low Storage
  RDSLowStorageAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasAlarmEmail
    Properties:
      AlarmName: !Sub ${EnvironmentName}-rds-low-storage
      AlarmDescription: RDS free storage space is low
      MetricName: FreeStorageSpace
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5000000000  # 5GB in bytes
      ComparisonOperator: LessThanThreshold
      AlarmActions:
        - !Ref AlarmTopic

Outputs:
  DashboardURL:
    Description: CloudWatch Dashboard URL
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${Dashboard}

  AlarmTopicArn:
    Description: SNS Topic ARN for alarms
    Condition: HasAlarmEmail
    Value: !Ref AlarmTopic
    Export:
      Name: !Sub ${EnvironmentName}-AlarmTopic-Arn



